"use client"

import { Roboto } from 'next/font/google'
import './globals.css'
import 'aos/dist/aos.css';
import AOS from 'aos';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';
import Header from '@/src/components/header/Header';
import Footer from '@/src/components/footer/Footer';


const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ["400", "500", "700"],
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const router = usePathname();
  const pathName = router;
  const [url, setUrl] = useState("");

  useEffect(() => {
    setUrl(pathName);
  }, [pathName]);

  useEffect(() => {
    AOS.init()
  }, [])



  return (
    <html lang="en">
      <body className={roboto.className}>
        {url.includes("admin") ? <></> : <Header />}
        {children}
        {url.includes("admin") ? <></> : <Footer />}
        </body>
    </html>
  )
}
